RGBLIGHT_ENABLE = no    # Enable WS2812 RGB underlight.
RGB_MATRIX_ENABLE  = WS2812
MOUSEKEY_ENABLE = no    # Mouse keys
OLED_ENABLE     = yes
OLED_DRIVER_ENABLE = yes
# OLED_DRIVER     = ssd1306
LTO_ENABLE      = yes
WPM_ENABLE = yes
